env:
  node: true
  es6: true
  browser: true
extends:
  - 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
    legacyDecorators: true
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  "no-unused-vars":
    - 0
  "no-console": 0
  "keyword-spacing":
    - error
  "no-mixed-spaces-and-tabs":
    - error
  "object-curly-spacing":
    - error
    - always
  "no-trailing-spaces":
    - error
