version: '3'
services:
  auth:
    image: felixbreuer/instapy-auth:latest
    restart: unless-stopped
    network_mode: bridge
    environment:
      - MONGO_URL
      - JWT_SECRET
      - VIRTUAL_HOST=auth.instapy.io
      - LETSENCRYPT_HOST=auth.instapy.io
  config:
    image: felixbreuer/instapy-config:latest
    restart: unless-stopped
    network_mode: bridge
    environment:
      - MONGO_URL
      - JWT_SECRET
      - CIPHER_SECRET
      - VIRTUAL_HOST=config.instapy.io
      - LETSENCRYPT_HOST=config.instapy.io
  socket:
    image: felixbreuer/instapy-socket:latest
    restart: unless-stopped
    network_mode: bridge
    environment:
      - JWT_SECRET
      - VIRTUAL_HOST=socket.instapy.io
      - LETSENCRYPT_HOST=socket.instapy.io
  nginx:
    image: nginx
    volumes:
      - /path/to/index.html/and/main.bundle.js:/usr/share/nginx/html:ro
      - /path/to/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
    - "80"
    restart: unless-stopped
    network_mode: bridge #needs to be checked if this works
    environment:
      - JWT_SECRET
      - VIRTUAL_HOST=www.instapy.io,instapy.io
      - LETSENCRYPT_HOST=www.instapy.io,instapy.io 